[package]
name = "dovero"
version = "0.1.0"
authors = ["Luciano Vernaschi <luciano@cromoteca.com>"]
edition = "2018"

[dependencies]
web-view = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"